---
- name: Install Ruby
  hosts: all
  tags: app-tag
  become: true
  vars:
    pkgs4ruby:
      - ruby-full
      - ruby-bundler
      - build-essential
  tasks:
    - name: Install Ruby by apt
      apt:
        name: "{{ pkgs4ruby }}"
        update_cache: yes
