---
- name: Install MongoDB
  hosts: all
  tags: db-tag
  become: true
  tasks:
    - name: Add apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
        state: present
    - name: Add apt repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: mongodb-org-3.2.list
    - name: Install MongoDB by apt
      apt:
        name: "mongodb-org"
        update_cache: yes
    - name: Enable mongod service
      systemd:
        daemon_reload: yes
        name: mongod
        enabled: yes
